'use client';

import { useState } from 'react';
import { FiDownload } from 'react-icons/fi';

interface FileDownloadProps {
  onDownload: (port: number) => Promise<void>;
  isDownloading: boolean;
}

export default function FileDownload({ onDownload, isDownloading }: FileDownloadProps) {
  const [inviteCode, setInviteCode] = useState('');
  const [error, setError] = useState('');
  
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    
    const port = parseInt(inviteCode.trim(), 10);
    if (isNaN(port) || port <= 0 || port > 65535) {
      setError('Please enter a valid code number (1-65535)');
      return;
    }
    
    try {
      await onDownload(port);
    } catch (err) {
      setError('Failed to download the file. Please check the invite code and try again.');
    }
  };
  
  return (
    <div className="space-y-6">
      <div className="bg-blue-500/10 border border-blue-500/20 p-4 rounded-xl">
        <h3 className="text-sm font-semibold text-blue-100 uppercase tracking-wider mb-1">Receive a File</h3>
        <p className="text-xs text-slate-100">
          Enter the invite code (which is the server port) generated by the sender to establish a direct download bridge.
        </p>
      </div>
      
      <form onSubmit={handleSubmit} className="space-y-5">
        <div>
          <label htmlFor="inviteCode" className="block text-xs font-semibold uppercase tracking-wider text-white mb-2">
            Invite Code
          </label>
          <input
            type="text"
            id="inviteCode"
            value={inviteCode}
            onChange={(e) => setInviteCode(e.target.value)}
            placeholder="e.g. 54321"
            className="input-field"
            disabled={isDownloading}
            required
            autoComplete="off"
          />
          {error && <p className="mt-2 text-xs font-medium text-rose-400">{error}</p>}
        </div>
        
        <button
          type="submit"
          className="btn-primary flex items-center justify-center w-full space-x-2"
          disabled={isDownloading}
        >
          {isDownloading ? (
            <span>Connecting...</span>
          ) : (
            <>
              <FiDownload className="w-5 h-5 shrink-0" />
              <span>Download File</span>
            </>
          )}
        </button>
      </form>
    </div>
  );
}
